/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSkillsRouteImport } from './routes/settings/skills'
import { Route as SettingsExtensionsRouteImport } from './routes/settings/extensions'
import { Route as SettingsConnectionRouteImport } from './routes/settings/connection'
import { Route as SettingsAuthRouteImport } from './routes/settings/auth'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/settings/skills',
  path: '/settings/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/settings/extensions',
  path: '/settings/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/settings/connection',
  path: '/settings/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuthRoute = SettingsAuthRouteImport.update({
  id: '/settings/auth',
  path: '/settings/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/settings/auth': typeof SettingsAuthRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions/$sessionId'
    | '/settings/auth'
    | '/settings/connection'
    | '/settings/extensions'
    | '/settings/skills'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions/$sessionId'
    | '/settings/auth'
    | '/settings/connection'
    | '/settings/extensions'
    | '/settings/skills'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/sessions/$sessionId'
    | '/settings/auth'
    | '/settings/connection'
    | '/settings/extensions'
    | '/settings/skills'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SettingsAuthRoute: typeof SettingsAuthRoute
  SettingsConnectionRoute: typeof SettingsConnectionRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/settings/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/settings/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/settings/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/auth': {
      id: '/settings/auth'
      path: '/settings/auth'
      fullPath: '/settings/auth'
      preLoaderRoute: typeof SettingsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SettingsAuthRoute: SettingsAuthRoute,
  SettingsConnectionRoute: SettingsConnectionRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
